---
apiVersion: v1
kind: Namespace
metadata:
  name: dandelion-mainnet
---
apiVersion: v1
kind: Namespace
metadata:
  name: dandelion-testnet
---
apiVersion: v1
kind: Namespace
metadata:
  name: observe
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
