apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/gimbalabs/dandelion/kustomize-dandelion.git
    targetRevision: {{ .Values.git.targetRevision | default "HEAD" }}
    path: applications/observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  destination:
    namespace: observe
    server: https://kubernetes.default.svc
