apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dandelion-
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:speedwing/kubernetes-staking.git
    targetRevision: {{ .Values.git.targetRevision }}
    path: kubernetes/applications/grafana-dashboards

  destination:
    namespace: observe
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
