apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dandelion-{{ .Values.cardano.network }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    - repoURL: {{ .Values.git.repositoryUrl }}
      targetRevision: {{ .Values.git.targetRevision }}
      path: overlays/{{ .Values.cardano.network }}-base
{{- if .Values.dandelion.cardano_db_sync.enabled -}}
    - repoURL: {{ .Values.git.repositoryUrl }}
      targetRevision: {{ .Values.git.targetRevision }}
      path: base/cardano-db-sync
{{- end }}


  destination:
    namespace: dandelion-testnet
    server: {{ .Values.spec.destination.server }}
