---
apiVersion: v1
kind: Service
metadata:
  name: dandelion-metrics-exporter
  labels:
    app.kubernetes.io/name: dandelion-metrics-exporter
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
  - name: metrics
    port: 9999
    targetPort: 9999
    protocol: TCP
  selector:
    io.kompose.service: dandelion-metrics-exporter
