namespace: dandelion-mainnet
#namePrefix: ptn0-
commonLabels:
  environment: production
  cardano_network: mainnet
  cardano_node_type: haskell
  project_name: dandelion
commonAnnotations:
  note: free-apis!
generators:
- helm-chartInflator-postgres-ha.yaml
bases:
- ../../base/cardano-db-sync
- ../../base/cardano-explorer-api
- ../../base/cardano-graphql
- ../../base/cardano-hasura
- ../../base/cardano-node
- ../../base/cardano-submit-api
resources:
- resources/common-env-configmap.yaml
- resources/ingress.yaml

patches:
# cardano-node
- path: patches/cardano-node-pvc.yaml
  target:
    kind: StatefulSet
    name: cardano-node
- path: patches/postgres-ha-pvc.yaml
  target:
    kind: StatefulSet
    name: init0-postgresql-ha-postgresql
