apiVersion: v1
kind: ConfigMap
metadata:
  name: cardano-db-sync-configmap
data:
  create-db-ro-user-entrypoint: |
    export PGPASSWORD=${POSTGRES_PASSWORD}
    while [ -z "$(psql -U ${POSTGRES_USER} -h ${POSTGRES_HOST} -c '\dt' ${POSTGRES_DB} | grep epoch)" ]
    do
      sleep 1
    done
    psql -U ${POSTGRES_USER} -h ${POSTGRES_HOST} -f /configmap/fixme.sql ${POSTGRES_DB}
  fixme.sql: |
    CREATE ROLE postgrest_ro;
    GRANT CONNECT ON DATABASE cdbs TO postgrest_ro;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO postgrest_ro;
    GRANT USAGE ON SCHEMA public TO postgrest_ro;
    ALTER ROLE postgrest_ro WITH login;
    ALTER USER postgrest_ro WITH PASSWORD 'CHANGEME';
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA PUBLIC TO postgrest_ro;
  liveness-healthcheck: |
    KUBE_API_URL=https://kubernetes.default.svc/api/v1/namespaces
    KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
    NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
    curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" ${KUBE_API_URL}/${NAMESPACE}/pods/cardano-db-sync-0/log?container=cardano-db-sync | tail -n10 | grep -q "insert.*Block.*epoch.*slot.*block.*hash\|getHistoryInterpreter"
