apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cardano-graphql
  name: cardano-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cardano-graphql
  template:
    metadata:
      labels:
        io.kompose.service: cardano-graphql
    spec:
      initContainers:
      - name: configure
        command: ["bash", "/configmap/initContainer-entrypoint"]
        image: repsistance/cardano-node:iohk-mn-passive-1.21.1
        imagePullPolicy: "Always"
        volumeMounts:
        - name: cardano-graphql-config
          mountPath: /config
        - name: cardano-graphql-configmap
          mountPath: /configmap
      containers:
      - env:
        - name: ALLOW_INTROSPECTION
          value: "true"
        - name: CACHE_ENABLED
          value: "true"
        - name: GENESIS_FILE_BYRON
          value: /config/genesis-byron.json
        - name: GENESIS_FILE_SHELLEY
          value: /config/genesis-shelley.json
        - name: HASURA_URI
          value: http://hasura-headless:8080
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: common-env
              key: POSTGRES_HOST_RW
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: common-env
              key: POSTGRES_PORT
        - name: POSTGRES_DB_FILE
          value: /run/secrets/common-env/POSTGRES_DB
        - name: POSTGRES_USER_FILE
          value: /run/secrets/common-env/POSTGRES_USER
        - name: POSTGRES_PASSWORD_FILE
          value: /run/secrets/postgres-password/POSTGRES_PASSWORD
        image: inputoutput/cardano-graphql:3.0.0
        #command: ["sh", "-c", "while true; do sleep 6969; done"]
        imagePullPolicy: Always
        name: cardano-graphql
        ports:
        - containerPort: 3100
        readinessProbe:
          tcpSocket:
            port: 3100
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 3100
          initialDelaySeconds: 15
          periodSeconds: 15
        resources: {}
        volumeMounts:
        - name: cardano-graphql-config
          mountPath: /config
        - name: common-env
          mountPath: /run/secrets/common-env
          readOnly: true
        - name: postgres-password
          mountPath: /run/secrets/postgres-password
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: cardano-graphql-config
        persistentVolumeClaim:
          claimName: cardano-graphql-config
      - name: cardano-graphql-configmap
        configMap:
          name: cardano-graphql-configmap
      - name: common-env
        configMap:
          name: common-env
      - name: postgres-password
        secret:
          secretName: init0-postgresql-ha-postgresql
          items:
          - key: postgresql-password
            path: POSTGRES_PASSWORD
