apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ogmios
  name: ogmios
spec:
  ports:
  - name: "1337"
    port: 1337
    targetPort: 1337
  selector:
    io.kompose.service: ogmios
status:
  loadBalancer: {}
